name: Build Twoyi
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install cargo-xdk
        run: cargo install cargo-xdk

      - name: Install NDK r22b
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r22b-linux-x86_64.zip
          unzip -q android-ndk-r22b-linux-x86_64.zip
          # Kita set ANDROID_NDK_HOME agar cargo-xdk tahu lokasi NDK-nya
          echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r22b" >> $GITHUB_ENV

      - name: Build Rust Library Manually
        run: |
          cd app/rs
          export ANDROID_NATIVE_API_LEVEL=21
          cargo xdk build --target aarch64-linux-android --release
          
          mkdir -p ../src/main/jniLibs/arm64-v8a
          cp target/aarch64-linux-android/release/libtwoyi.so ../src/main/jniLibs/arm64-v8a/

      - name: Build Android APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug -x :app:cargoBuild

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Twoyi-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
